import React from 'react'
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Navbar } from '../Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function MainLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className={styles.container}>
                <Head>
                        <title>Contact Page</title>
                        <meta name="description" content="Generated by create next app" />
                        <meta name="viewport" content="width=device-width, initial-scale=1" />
                        <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar />
                <main className={`${styles.main} ${inter.className}`}>
                    {children}
                </main>
        </div>
    )
}
